import { ElevatorModel, CabinOption, AccessoryOption, FAQItem } from '@/types/elevator';

export const ELEVATOR_MODELS: ElevatorModel[] = [
  {
    id: 'g1-classic-manual-acp',
    name: 'G+1 Classic (Manual Door, ACP)',
    type: 'G+1',
    category: 'Classic',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'ACP',
    basePrice: 500000,
    description: 'Cost-effective basic elevator with MS cabin',
    features: ['MS Cabin', 'Manual Sliding Door', 'ACP Enclosure', '2 Landings'],
  },
  {
    id: 'g1-classic-manual-glass1',
    name: 'G+1 Classic (Manual Door, 1-Side Glass)',
    type: 'G+1',
    category: 'Classic',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'Glass-1Side',
    basePrice: 550000,
    description: 'Classic elevator with elegant glass enclosure',
    features: ['MS Cabin', 'Manual Sliding Door', 'Glass Enclosure (1 Side)', '2 Landings'],
  },
  {
    id: 'g1-classic-manual-glass2',
    name: 'G+1 Classic (Manual Door, 2-Sides Glass)',
    type: 'G+1',
    category: 'Classic',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'Glass-2Sides',
    basePrice: 580000,
    description: 'Classic elevator with premium dual glass panels',
    features: ['MS Cabin', 'Manual Sliding Door', 'Glass Enclosure (2 Sides)', '2 Landings'],
  },
  {
    id: 'g1-ultra-manual-acp',
    name: 'G+1 Ultra (Manual Door, ACP)',
    type: 'G+1',
    category: 'Ultra',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'ACP',
    basePrice: 570000,
    description: 'Premium SS304 cabin with ACP enclosure',
    features: ['SS304 Cabin', 'Manual Sliding Door', 'ACP Enclosure', '2 Landings'],
  },
  {
    id: 'g1-ultra-manual-glass1',
    name: 'G+1 Ultra (Manual Door, 1-Side Glass)',
    type: 'G+1',
    category: 'Ultra',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'Glass-1Side',
    basePrice: 620000,
    description: 'Premium SS304 cabin with glass elegance',
    features: ['SS304 Cabin', 'Manual Sliding Door', 'Glass Enclosure (1 Side)', '2 Landings'],
  },
  {
    id: 'g1-ultra-manual-glass2',
    name: 'G+1 Ultra (Manual Door, 2-Sides Glass)',
    type: 'G+1',
    category: 'Ultra',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'Glass-2Sides',
    basePrice: 650000,
    description: 'Premium SS304 cabin with stunning dual glass',
    features: ['SS304 Cabin', 'Manual Sliding Door', 'Glass Enclosure (2 Sides)', '2 Landings'],
  },
  {
    id: 'g2-classic-manual-acp',
    name: 'G+2 Classic (Manual Door, ACP) - CFM',
    type: 'G+2',
    category: 'Classic',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'ACP',
    basePrice: 570000,
    description: "Customer's Favorite Model - Best seller with 3 landings",
    features: ['MS Cabin', 'Manual Sliding Door', 'ACP Enclosure', '3 Landings', 'Best Seller'],
  },
  {
    id: 'g2-ultra-manual-glass1',
    name: 'G+2 Ultra (Manual Door, 1-Side Glass)',
    type: 'G+2',
    category: 'Ultra',
    sizes: ['3x3', '3.6x3.6', '4x4'],
    doorType: 'Manual',
    enclosure: 'Glass-1Side',
    basePrice: 720000,
    description: 'Premium 3-landing elevator with glass elegance',
    features: ['SS304 Cabin', 'Manual Sliding Door', 'Glass Enclosure (1 Side)', '3 Landings'],
  },
];

export const ACCESSORIES: AccessoryOption[] = [
  { id: 'ms-swing-half', name: 'MS Swing Door (Half Vision)', price: 15000, description: 'MS swing door with half glass panel' },
  { id: 'ms-swing-full', name: 'MS Swing Door (Full Vision)', price: 20000, description: 'MS swing door with full glass panel' },
  { id: 'ss-swing-half', name: 'SS Swing Door (Half Vision)', price: 25000, description: 'SS304 swing door with half glass' },
  { id: 'ss-swing-full', name: 'SS Swing Door (Full Vision)', price: 30000, description: 'SS304 swing door with full glass' },
  { id: 'rf-lop', name: 'RF & Password (LOP)', price: 10000, description: 'RF device with password for landing panel' },
  { id: 'rf-cop', name: 'RF & Password (COP)', price: 15000, description: 'RF device with password for car panel' },
  { id: 'fingerprint-lop', name: 'Fingerprint & Password (LOP)', price: 15000, description: 'Biometric security for landing panel' },
  { id: 'fingerprint-cop', name: 'Fingerprint & Password (COP)', price: 20000, description: 'Biometric security for car panel' },
  { id: 'touchscreen-lop', name: 'Touch Screen LOP', price: 3000, description: 'Modern touch interface for landing' },
  { id: 'touchscreen-cop', name: 'Touch Screen COP', price: 20000, description: 'Modern touch interface for cabin' },
  { id: 'converter', name: 'Phase Converter', price: 20000, description: 'Single phase to 3 phase converter' },
  { id: 'iot-controller', name: 'Smart IoT Controller', price: 80000, description: 'Cloud monitoring and remote control' },
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq1',
    category: 'General',
    question: 'What is a home elevator?',
    answer: 'A home elevator is a small lift designed to transport people and goods between different floors of a residential building.',
  },
  {
    id: 'faq2',
    category: 'Installation',
    question: 'How much space is required for installation?',
    answer: 'GPlus home elevators can be installed in minimal space, typically requiring around 3x3 feet. If installed on the flooring level, a minimum of 6 inches to 1 foot may be required.',
  },
  {
    id: 'faq3',
    category: 'Installation',
    question: 'Do I need civil work for installation?',
    answer: 'No, our home elevators are designed for easy installation without extensive civil work. We can perform core cutting for existing homes to facilitate installation.',
  },
  {
    id: 'faq4',
    category: 'Safety',
    question: 'Is the home elevator safe?',
    answer: 'Yes, GPlus elevators adhere to safety standards and include features like emergency stop buttons, automatic braking systems, and ARD (Automatic Rescue Device) for power outages.',
  },
  {
    id: 'faq5',
    category: 'Capacity',
    question: 'How many people can the elevator accommodate?',
    answer: 'Our small home elevators are designed to carry up to 3-5 people comfortably or equivalent to 220 kgs.',
  },
  {
    id: 'faq6',
    category: 'Installation',
    question: 'What is the installation time?',
    answer: 'Standard models take 10-15 working days for fabrication and 5-10 working days for installation. Customized models may take longer.',
  },
  {
    id: 'faq7',
    category: 'Pricing',
    question: 'What is the price range for a GPlus home elevator?',
    answer: 'Prices range from ₹5,00,000 to ₹7,20,000 depending on the model, size, door type, and enclosure options. Contact us for a detailed quote.',
  },
  {
    id: 'faq8',
    category: 'Maintenance',
    question: 'Is maintenance required?',
    answer: 'Yes, regular maintenance is recommended. We offer Basic AMC (₹8,000-17,000/year) and Comprehensive AMC (₹30,000-55,000/year) packages.',
  },
  {
    id: 'faq9',
    category: 'Features',
    question: 'What happens during a power outage?',
    answer: 'Our elevators are equipped with ARD (Automatic Rescue Device) with backup batteries to ensure safe operation during power outages, allowing you to reach your destination safely.',
  },
  {
    id: 'faq10',
    category: 'Customization',
    question: 'Can I customize the design?',
    answer: 'Absolutely! We offer various cabin options (MS, SS, Gold), enclosure types (ACP, Glass), door types (Manual, Auto), and multiple accessories for complete customization.',
  },
];

export const QUICK_REPLIES = {
  initial: [
    'View Products',
    'Calculate Price',
    'FAQs',
    'Request Quote',
    'Contact Us',
  ],
  products: [
    'G+1 Models',
    'G+2 Models',
    'G+3 Models',
    'Compare Models',
    'Back to Menu',
  ],
  support: [
    'Installation Process',
    'Maintenance Info',
    'Safety Features',
    'Customization Options',
    'Back to Menu',
  ],
};

export const COMPANY_INFO = {
  name: 'GPlus Elevator',
  website: 'www.gpluselevator.com',
  phone: ['+91 9363613828', '+91 9363603828'],
  email: 'gpluselevator@gmail.com',
  tagline: 'Next Generation Vertical Transportation Technology',
};